// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tebsafpyccclslhhjsjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlYnNhZnB5Y2NjbHNsaGhqc2p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjMzODEsImV4cCI6MjA2NzYzOTM4MX0.FspMkIG51DcT4WwCL1aB7F8CV1pjOco16Ccs8UeiwGg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});